/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#10131a",
        "surface-container-high": "#272a31",
        "inverse-on-surface": "#2e3038",
        "tertiary": "#ffb786",
        "on-secondary": "#263143",
        "primary-container": "#4d8eff",
        "inverse-primary": "#005ac2",
        "secondary-container": "#3e495d",
        "surface-container": "#1d2027",
        "on-tertiary": "#502400",
        "surface-dim": "#10131a",
        "tertiary-fixed-dim": "#ffb786",
        "inverse-surface": "#e1e2ec",
        "on-error": "#690005",
        "secondary-fixed": "#d8e3fb",
        "outline-variant": "#424754",
        "on-primary": "#002e6a",
        "on-secondary-fixed": "#111c2d",
        "tertiary-container": "#df7412",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-fixed-variant": "#3c475a",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-background": "#e1e2ec",
        "surface-container-low": "#191b23",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#311400",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed": "#001a42",
        "surface-container-highest": "#32353c",
        "on-error-container": "#ffdad6",
        "primary": "#adc6ff",
        "surface-tint": "#adc6ff",
        "secondary": "#bcc7de",
        "outline": "#8c909f",
        "on-surface": "#e1e2ec",
        "surface-bright": "#363941",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#0b0e15",
        "background": "#10131a",
        "on-tertiary-container": "#461f00",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-container": "#aeb9d0",
        "on-primary-fixed-variant": "#004395",
        "surface-variant": "#32353c",
        "on-primary-container": "#00285d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "margin-mobile": "16px",
        "sm": "16px",
        "md": "24px",
        "xs": "8px",
        "gutter": "24px",
        "xl": "80px",
        "lg": "48px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "code-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
